/*
  One-time (re-runnable) script: self-host the Google Fonts this site uses.
  Downloads latin + latin-ext woff2 subsets for Caveat, Spectral, and
  JetBrains Mono into public/fonts/ and generates src/styles/fonts.css
  with matching @font-face rules (font-display: swap).

  Why: removes a render-blocking third-party request and the GDPR concern
  of shipping visitor IPs to Google Fonts from an EU-hosted personal site.

  Usage: node scripts/fetch-fonts.mjs
*/
import { mkdir, writeFile } from 'node:fs/promises';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Caveat:wght@500;600;700&family=Spectral:ital,wght@0,400;0,500;0,600;1,400&family=JetBrains+Mono:wght@400;500&display=swap';
// A modern browser UA so Google serves woff2 with unicode-range subsets
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`fonts css fetch failed: ${res.status}`);
const css = await res.text();

// Parse blocks of: /* subset */ @font-face { ... }
const blockRe = /\/\* ([\w-]+) \*\/\s*(@font-face\s*\{[^}]+\})/g;
const keepSubsets = new Set(['latin', 'latin-ext']);
const out = [];
const downloads = new Map(); // url -> local filename

for (const m of css.matchAll(blockRe)) {
  const [, subset, block] = m;
  if (!keepSubsets.has(subset)) continue;
  const family = block.match(/font-family:\s*'([^']+)'/)[1];
  const style = block.match(/font-style:\s*(\w+)/)[1];
  const weight = block.match(/font-weight:\s*(\d+)/)[1];
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)[1];

  const slug = family.toLowerCase().replace(/\s+/g, '-');
  // Variable fonts serve the same file for several weights — reuse the
  // first filename assigned to a URL so every @font-face block points at
  // a file that actually exists.
  let fname = downloads.get(url);
  if (!fname) {
    fname = `${slug}-${weight}${style === 'italic' ? 'i' : ''}-${subset}.woff2`;
    downloads.set(url, fname);
  }
  out.push(
    `/* ${family} ${weight}${style === 'italic' ? ' italic' : ''} (${subset}) */\n` +
      block.replace(/url\(https:[^)]+\.woff2\)/, `url(/fonts/${fname})`)
  );
}

await mkdir(new URL('../public/fonts/', import.meta.url), { recursive: true });
let bytes = 0;
for (const [url, fname] of downloads) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`font fetch failed ${url}: ${r.status}`);
  const buf = Buffer.from(await r.arrayBuffer());
  bytes += buf.length;
  await writeFile(new URL(`../public/fonts/${fname}`, import.meta.url), buf);
  console.log(`  ${fname}  ${(buf.length / 1024).toFixed(1)} KB`);
}

await writeFile(
  new URL('../src/styles/fonts.css', import.meta.url),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n\n${out.join('\n\n')}\n`
);
console.log(`\n${downloads.size} files, ${(bytes / 1024).toFixed(0)} KB total. Wrote src/styles/fonts.css`);
